[default]
MONGO_DATABASE_NAME = "Nome do banco de dados do seu bot rodando na produção"
MONGO_CONNECTION_STRING = "Link de conexão ao seu banco de dados Mongo"
TELEGRAM_API_ID = "Veja qual em my.telegram.org"
TELEGRAM_API_HASH = "Veja qual em my.telegram.org"
TELEGRAM_APP_NAME = "Nome do arquivo de sessão do seu bot"
TELEGRAM_BOT_TOKEN = "Token do seu bot (disponível no @BotFather)"